### ISSUE TITLE
Support mixins 

### ISSUE THREAD

**Issue by AlexanderShushunov** [redneckz/react-bem-helper#8]
It will be very convenient to use an `element` function to mixin element classes to an existing block.
E.g.
```javascript
const BlockA = block("block-a")(...);
const BlockB = block("block-B")(() => (
    <Element />
));
const Element = element('element')(BlockA);
```

Now `BlockA` has an inappropriate name. So an assertion occurs.

**Comment by redneckz** [comment]
Fixed
